EVALUATE
SUMMARIZECOLUMNS
(
	'Date'[Month],
	'Bookstore'[BookstoreName],
	FILTER('Date','Date'[Year]= "2015" && 'Date'[Month] = "May"),
	"Profit", [Sale profit],
	"Profit prev month", CALCULATE([Sale profit], PREVIOUSMONTH('Date'[Date]))
)
ORDER BY 'Bookstore'[BookstoreName]